spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/turtlecoin
    username: postgres
    password: network
